### ISSUE TITLE
Visual Studio Runtime library selection

### ISSUE THREAD

**Issue by howprice** [bkaradzic/genie#103]
Is it possible to select the RuntimeLibrary for the generated Visual Studio project files?

In my case I am linking against the pre-built SDL2 Development libraries for Windows. For compatibility with SDL2main.lib I would like *both* my Debug and Release configurations to use the Multi-threaded DLL (/MD) runtime rather than the Debug configuration defaulting to use the Multi-threaded Debug DLL (/MDd). Is this possible?

**Comment by bkaradzic** [comment]
This was recently added by @ryanjuckett, maybe he can answer this?

**Comment by ryanjuckett** [comment]
You should be able to force the release runtime library by adding the ReleaseRuntime flag to your configuration. There is also a DebugRuntime flag to force the opposite direction. (I'm out of town and on my phone so apologies for the lack of an example).

**Comment by howprice** [comment]
That works thanks.

**Comment by ddengster** [comment]
This seems to be broken for vs2019. `DebugRuntime` and `ReleaseRuntime` doesn't seem to do anything, and even [hacking](https://github.com/bkaradzic/GENie/blob/f9bd455a8439dbcb807816c0be9e4aedf5991bc3/src/actions/vstudio/vstudio_vcxproj.lua#L282) in `Managed` doesn't seem to change the /MT option. Any ideas?

@ryanjuckett
