### ISSUE TITLE
GENie Unity Builds

### ISSUE THREAD

**Issue by v3n** [bkaradzic/genie#106]
Is there a good way to do Unity builds in GENie besides having to architect a special source file with includes? (This seems to me that this is a good use of GENie to maintain a single source of build information-the genie.lua file).

I'm willing to work on a flag that generates the unity files based on each line of your `files {}` declaration if you think this is within the scope of GENie. (i.e. `files { "src/math/**.cpp, "src/gfx/**.cpp" }` would result in `src-math-unity.cpp` and a `src-gfx-unity.cpp` files that had all the respective includes).

**Comment by bkaradzic** [comment]
Source has to be buildable as amalgmated build, it's not build system that enables it. This feature just might cause all kinds of support request.

**Comment by v3n** [comment]
Makes sense, was just curious. Thanks!

**Comment by bkaradzic** [comment]
No problem. One thing you might want to try is to script that inside your build script.

**Comment by v3n** [comment]
Will do, thanks for the advice.
