### ISSUE TITLE
os_getversion is still referenced in genie.make for bsd and solaris 

### ISSUE THREAD

**Issue by shattered** [bkaradzic/genie#109]
and that makes Genie unusable.

**Comment by shattered** [comment]
whoa, does this mean genie drops support for those platforms?

**Comment by bkaradzic** [comment]
It means it might work there or might not, but I don't promise anything. I have no way to test it on Solaris nor BSD. Just the fact that works on OSX and Linux means might be trivial to get it up and running on other *nix OS.
