### ISSUE TITLE
Visual Studio - Target Platform Version

### ISSUE THREAD

**Issue by kretash** [bkaradzic/genie#117]
I don't think that there's a way to change the target platform version in the general settings in visual studio. The project has 8.1 by default and I have to change it to 10.0.10240.0 every time I build. Not a big issue but it would be cool to be able to set it.

Thanks.

**Comment by bkaradzic** [comment]
Check this out: https://github.com/bkaradzic/bx/blob/master/scripts/toolchain.lua#L52

Is this VS2015 issue? Target WinPhone?

**Comment by neilogd** [comment]
I added support for this a while ago:

https://github.com/Psybrus/Psybrus/blob/develop/Scripts/Toolchain.lua#L435

**Comment by bkaradzic** [comment]
Not sure I get it what it does? In bgfx D3D12 compiles without this target version.

**Comment by neilogd** [comment]
Wouldn't build for me due to missing d3d12.h and what not, since the
headers don't exist in the Windows 8.1 SDK. I'm gonna pull down bgfx now
and build up the projects just to check what's actually different.

Anyways, that will allow you to pick the SDK you wish to build against if
you use it. Defaults to Windows 8.1 SDK for VS2015.

**Comment by neilogd** [comment]
Dynamically loading it, and having the D3D12 headers packaged up with bgfx
would be why :) Whereas I'm statically linking in my own codebase, and
including from the Windows 10 SDK. Easily explained then.

**Comment by bkaradzic** [comment]
Ah, ok. Early on when I didn't dynamically load it for bgfx, D3D12 headers were in 8.1 SDK for me.

**Comment by neilogd** [comment]
Yeah I remember that. After release I think it just all got relegated to the Win10 SDK, which I guess makes sense now.

**Comment by bkaradzic** [comment]
Updated readme with info about `windowstargetplatformversion`.
