### ISSUE TITLE
Getting started with emscripten

### ISSUE THREAD

**Issue by ggcarlton** [bkaradzic/GENie#129]
I'm starting to use GENie and I've got stuck on getting Emscripten working.  I've got a simple project working for windows with the following genie.lua file:

solution "MyApplication"
   configurations { "Debug", "Release" }
   -- A project defines one build target
   project "MyApplication"
      kind "ConsoleApp"
      language "C++"
      files { "../source/**.h", "../source/**.cpp" }
      targetdir "bin/%{cfg.buildcfg}"
      configuration "Debug"
         defines { "DEBUG" }
         flags { "Symbols" }
      configuration "Release"
         defines { "NDEBUG" }
         flags { "Optimize" }  

As an aside I found it hard to find anything at all that would help getting started.  The above file is from a google search that hit this page http://industriousone.com/sample-script, which is for premake not GENie, and also missing targetdir.  But with that addition, great, we're up and running for Visual Studio at least.

Now, for Emscripten.  I have Emscripten, MinGW, and vs-tool installed.

I can't find any docs, but there is the odd page with references to GENie, as in the following:
  https://github.com/bkaradzic/bgfx/issues/574

When I try that command line:
  genie --gcc=asmjs gmake

I get the error "invalid option 'gcc'".  Is that "gcc" some intrinsic part of GENie or is it something that the genie.lua file should interpret in order to set some stuff up manually?  From the error I'm guessing its the latter, but some documentation would really help.

**Comment by bkaradzic** [comment]
That's currently not a part of GENie. Toolchain setup used by bgfx is here:
https://github.com/bkaradzic/bx/blob/master/scripts/toolchain.lua#L11

You can use toolchain.lua inside your project or you can just pick "asmjs" setup from there.
