### ISSUE TITLE
gmake option produces lua error

### ISSUE THREAD

**Issue by ggcarlton** [bkaradzic/GENie#130]
Using the very basic script mentioned in this issue:
 https://github.com/bkaradzic/GENie/issues/129

With the command line "genie gmake" produces the following error:

[string "_MAKE = { }..."]:15: invalid use of '%' in replacement string
stack traceback:
        [C]: in function 'string.gsub'
        [string "_MAKE = { }..."]:15: in field 'esc'
        [string "premake.make.cpp = { }..."]:202: in field 'gmake_cpp_config'
        [string "premake.make.cpp = { }..."]:11: in local 'callback'
        [string "function premake.generate(obj, filename, call..."]:9: in field 'generate'
        [string "_MAKE = { }..."]:90: in field 'onproject'
        [string "premake.action = { }..."]:23: in field 'call'
        [string "_WORKING_DIR        = os.getcwd()..."]:67: in function '_premake_main'

My guess is a missing MinGW environment variable resulting in a non-obvious error message, but I've had a quick look through the genie source and can't see exactly what is going on.

**Comment by bkaradzic** [comment]
```targetdir "bin/%{cfg.buildcfg}"``` <- that doesn't look right

**Comment by ggcarlton** [comment]
Yes that was it.  I'm not sure where I got that line from, but replacing it with a newoption string and I'm up and running again.
