### ISSUE TITLE
Problem,linker errors.

### ISSUE THREAD

**Issue by piluve** [bkaradzic/GENie#133]
Hello!

The thing is,that I want to make a static lib project and then link it from another project.
The problem comes when I build the second project, because it gives me some "unresolved external syombol" errors.
Those errors come from another lib that is linked to the parent project.
Let me show you the genie config file:
http://pastebin.com/f5F6yvDG
So the question is: How should I do it? (I dont think its correct that I have to link it in both projects)
See you!

EDIT:
Let me explain how I would like the projects:

Engine(Static Lib)
+Linked with glew/glfw/etc
Game(.exe)
+Linked only with the engine lib

**Comment by bkaradzic** [comment]
Libraries are not linked to other libraries. Libraries get linked to create executable. So you just have to move those dependencies...

**Comment by piluve** [comment]
So, I will have to link  everything in the "exe " project?
Thanks!
