### ISSUE TITLE
Visual Studio 2015 sln wrong format

### ISSUE THREAD

**Issue by amerkoleci** [bkaradzic/GENie#134]
Genie generated sln contains second line "#Visual Studio 2015", it should be "Visual Studio 14".

**Comment by bkaradzic** [comment]
What it causes? I'm using VS2015 and don't see any issues...

**Comment by amerkoleci** [comment]
On windows file system the icon don't show 14.

**Comment by bkaradzic** [comment]
Didn't notice it. Anyhow if you have fix, just send PR.
