### ISSUE TITLE
File level configuration isn't possible

### ISSUE THREAD

**Issue by bradhugh** [bkaradzic/GENie#135]
Any file level configuration that could be done with premake is no longer possible after the change below. For instance, "buildaction" is broken due to this.  We also wouldn't be able to implement any new features that use file-level configuration.

"Update bake.lua to remove slow code path."

The genie bake postprocess function was building per-file
configurations very slowly. It relied heavily on numerous
nested pattern-matches but as far as I could tell, it
wasn't doing anything that resulted in a change to a project
or a makefile. This change removes the offending code.

**Comment by bradhugh** [comment]
That's commit 99e9888, sorry for omitting that.

**Comment by bkaradzic** [comment]
Can you make simple `genie.lua` file that demonstrate bug?

**Comment by bradhugh** [comment]
Here you go.
[filelevelconfig.zip](https://github.com/bkaradzic/GENie/files/174822/filelevelconfig.zip)

The file which defines the buildaction "Embed" for the txt file. It doesn't work without the code mentioned, but works fine once the code is added back.

**Comment by bkaradzic** [comment]
Is this just C# feature? I'm not using C# at all, and have no way to test it. Can you provide fix that doesn't affect C/C++?

**Comment by bradhugh** [comment]
This feature (C# buildaction) is the only feature I *currently* see using file-level configuration.  However, I'd like to create a new feature for C++ projects that would make use of this configuration.  In theory, other scenarios could use file-level configuration.  For instance, if you wanted to specify a different define for a specific file in a project.  The C# thing that's broken isn't important, it's the underlying feature that makes it possible to use configuration at the file-level.  I can't fix it for C# only because I want to use it in C++.  Make sense?

**Comment by bradhugh** [comment]
So I did some timing on the postprocess function and the code in question. It does take up more time than any other part of post-processing, but even on a debug build of genie, it's only taking 53 milliseconds even for large projects.  Can you try it? The performance hit seems negligible from my testing.

**Comment by bradhugh** [comment]
I submitted a pull request for this change. Feel free to test it.  The speed increase is minimal by removing this code.

**Comment by bradhugh** [comment]
Thanks for merging!
