### ISSUE TITLE
No way to specify UWP (storeapp 8.2) build

### ISSUE THREAD

**Issue by amaiorano** [bkaradzic/GENie#147]
Unless I'm missing something, it seems there's no way to set premake.vstudio.storeapp to "8.2" from command line or build script. I was able to test this path by building the debug version of genie and modifying _vstudio.lua to forcibly set it:

premake.vstudio.storeapp = "8.2"

Was this perhaps removed by accident at some point? I can see that WinRT support was added in this commit:

https://github.com/bkaradzic/GENie/commit/f3f0c96b88aa1e2dbc47420f15cf931bc12fd620#diff-b6ae0f898e3cd7be37b57806b442714b

**Comment by bkaradzic** [comment]
This is how you do it:
https://github.com/bkaradzic/bx/blob/master/scripts/toolchain.lua#L374

https://github.com/bkaradzic/bx/blob/master/scripts/toolchain.lua#L58

**Comment by amaiorano** [comment]
Thank you for the quick response. Just curious, shouldn't this be exposed as part of Genie?

**Comment by bkaradzic** [comment]
It is exposed. toolchain.lua is just my GENie script, you might want to configure yours differently.

**Comment by amaiorano** [comment]
I guess I just find it weird having to modify a variable like vstudio.storeapp directly from my client script, since the rest of the interface is done via functions like configuration, defines, flags, etc. Also these variables aren't documented on the scripting reference page (https://github.com/bkaradzic/genie/blob/master/docs/scripting-reference.md#scripting-reference)

**Comment by bkaradzic** [comment]
Original Premake has `--platform`, `--os`, etc. switches, but in general case that complicates usage, and I plan to deprecate it. You don't want to spell out all that all the time, you just want to update your script with all options, and invoke GENie with minimum number of arguments.
