### ISSUE TITLE
freebsd build

### ISSUE THREAD

**Issue by velkyel** [bkaradzic/GENie#194]
in makefile is variable OS setup to "bsd" (uname="FreeBSD"), but build/gmake.bsd doesn't exists.

It's possible to build it with small changes like: OS=linux and remove -ldl from LIBS in build/gmake.linux/genie.make but it's not fully correct solution.

**Comment by bkaradzic** [comment]
Can you verify my change? I don't use FreeBSD.

**Comment by bkaradzic** [comment]
@velkyel Did this work for you?

**Comment by velkyel** [comment]
yes it works.  There are some other issues in building bgfx -- specifically 3rdparty/ocornut-imgui/imgui_draw.cpp where alloca() is not found if IMGUI_DISABLE_STB_RECT_PACK_IMPLEMENTATION and IMGUI_DISABLE_STB_TRUETYPE_IMPLEMENTATION are enabled (some of stb includes stdlib.h).

In advance I'm encountering on problems with nvidia freebsd drivers.  Unfortunately I don't have so much time to investigate it in detail and now going rather back to debian testing :( I'm very sorry for your time spent on this issue.
