### ISSUE TITLE
genie.exe produces a Solution and Visual Studio can't build it

### ISSUE THREAD

**Issue by kungfooman** [bkaradzic/GENie#223]
Hi, I've already asked the question here:

http://stackoverflow.com/questions/39060927/genie-exe-produces-a-solution-and-visual-studio-cant-build-it

I guess the issue is pretty clear, that Visual Studio isn't able to generate the missing folders. But is there any option to change that? ATM I'm using premake5.exe, which works nicely, but I would like to have the Filters in Visual Studio.

I'm new to premake5/genie, so please dare with me, when something fundamentally is wrong. This is the script:

	solution "AliceDankEngine"
		location "vs2015_asd"
		platforms { "x32", "x64" }
		configurations { "Debug", "Release" }
		language "C++"
		kind "ConsoleApp"
		configuration "Debug"
			--links { debug_libs }
		configuration "Release"
			--links { release_libs }

		-- rtti "Off"
		-- flags { "ExtraWarnings", "StaticRuntime", "FloatFast", "EnableSSE2" }
		configuration "Debug"
			flags { "Symbols" }
			defines { "DEBUG" }
		configuration "Release"
			-- optimize "Speed"
			defines { "NDEBUG" }
			
	project "test"
		-- files { "source/*/*.cpp" }
		
		-- objdir "!obj/$(Platform)_$(Configuration)"
		files { "source/bgfx/*.cpp" }
		-- prebuildcommands {
		-- 	'echo fooooooooooooooo'
		-- }
		includedirs { "C:/Users/kung/Desktop/BGFX/bgfx/examples/common" }
		includedirs { "C:/Users/kung/Desktop/BGFX/bgfx/include" }
		includedirs { "C:/Users/kung/Desktop/BGFX/bx/include" }

		libdirs { "../lua/libs", "../zlib" }
		
		--links { "bgfx.lib" }

**Comment by bkaradzic** [comment]
It seems it's misconfigured. You should check bgfx GENie scripts, and see how it's configured. See .lua scripts here: https://github.com/bkaradzic/bgfx/tree/master/scripts

**Comment by kungfooman** [comment]
Hey, this has nothing to do with bgfx, I'm just using the lib.
