### ISSUE TITLE
gobjc++ required?

### ISSUE THREAD

**Issue by angelog** [bkaradzic/GENie#244]
Since updating to the latest version of GENie, it appears we are now required to have gobjc++ installed in order to build with gmake, or we'll get this error:
```
g++: error trying to exec 'cc1objplus': execvp: No such file or directory
```
It looks like this might have been added in commit 9f13e628? Not sure.

**Comment by angelog** [comment]
Referencing #239

**Comment by bkaradzic** [comment]
This is already fixed, closing it.
