### ISSUE TITLE
Add support for "Cocoa bundle" project types (Xcode)

### ISSUE THREAD

**Issue by KageKirin** [bkaradzic/GENie#251]
Hi,

would it be possible to add support for Xcode Cocoa "bundle" project types?
Bundles are in fact SharedLibs, with some plist metadata and enclosed in a `.bundle` folder. Xcode has a specific project type for them, which would tremendous helpful to have support for,
I.e. by adding a project `kind` `"Bundle"`, which would then generate the correct Xcode project type.

Why is this needed? I'm using GENie to generate my projects, in this case for Unity native plugin integration, and on macOS, Unity wants to get its plugins as `.bundle`, not dylibs.

**Comment by bkaradzic** [comment]
So since you're using (and you have ability to test it) it just follow SharedLib kind implementation and add Bundle. For other build systems Bundle should be just alias of SharedLib. It should be fairly simple.

**Comment by KageKirin** [comment]
Fair enough. Just got it working locally.
Are there some unittests to have passing before even submitting a pull request?

**Comment by bkaradzic** [comment]
Try building bx and bgfx with your changed GENie file.

**Comment by KageKirin** [comment]
Thanks for merging the PR.
I guess we can now close this issue.
