### ISSUE TITLE
Version 719 or 249?

### ISSUE THREAD

**Issue by Klowner** [bkaradzic/GENie#257]
I see the README states version 719, but `src/host/version.h` has 249. Do you only bump the `version.h` when you have a "release" or did this just get missed?

**Comment by bkaradzic** [comment]
`make dist` automatically bumps the version, compiles, and then reverts change. What's in version.h doesn't matter.

**Comment by bkaradzic** [comment]
This will make it more clear: https://github.com/bkaradzic/GENie/commit/26d7108eaf65bed82f963ae83cd056ed8ae7abf6

**Comment by Klowner** [comment]
Perfect, thank you!

I updated the Arch linux package to read from the `README`md` instead
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=genie-git

**Comment by bkaradzic** [comment]
Instead `make` here https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=genie-git#n21, do this:
```
genie release
make -C build/gmake.linux clean all
```

**Comment by bkaradzic** [comment]
That way you'll execute all scripts to get you version into executable.

**Comment by Klowner** [comment]
Got it! Thanks for the clarification, changed applied.
