### ISSUE TITLE
Issue removeflags when passing both "NoExceptions" and "NoRTTI"

### ISSUE THREAD

**Issue by hugoam** [bkaradzic/GENie#274]
I found a possible bug (using the toolchain script from bx but that might no matter)
Somehow this is okay :
````lua
project "test"
    kind "SharedLib"

    removeflags {
        "NoExceptions",
        --"NoRTTI",
    }
````
Producing a project where exceptions are enabled with VS2015

And this is okay :
````lua
project "test"
    kind "SharedLib"

    removeflags {
        --"NoExceptions",
        "NoRTTI",
    }
````
Producing a project where RTTI is enabled with VS2015

However this :
````lua
project "test"
    kind "SharedLib"

    removeflags {
        "NoExceptions",
        "NoRTTI",
    }
````
Doesn't produce the expected project.
Meaning I have no way to produce a project with both Exceptions and RTTI enabled at project scope.

**Comment by hugoam** [comment]
I found the issue.
The removevalues was removing from the list while iterating front-to-back which causes to skip one value.
By reverting both loops we fix the problem easily (we break anyway when the pattern is found so removing is not a problem then)
I cannot do a pull request since my fork has other changes for which I will do a pull request later but you can probably integrate this fix manually.
https://github.com/hugoam/GENie/commit/ec340a9174e7d19c09edc6c7a76388132df5646b

**Comment by hugoam** [comment]
Did you have time to look into this ? The fix is two lines and fixes a kind of important issue.

**Comment by bkaradzic** [comment]
Can you submit PR?
