### ISSUE TITLE
Set a VapiDir on valac

### ISSUE THREAD

**Issue by KernelFreeze** [bkaradzic/GENie#286]
It would be great if you could add a --vapidir without the use of a hack like buildoptions {"-03 --vapidir=vapi"} when using a Vala project.

**Comment by bkaradzic** [comment]
Maybe @taylor001 can look at it?

**Comment by taylor001** [comment]
I guess something like this would be sufficient?

    vapidirs {
        "<dir_a>",
        "<dir_b>",
        ...
    }

    buildoptions_vala {
        "--gresources=...",
        "--target-glib=2.38",
        ...
    }

**Comment by taylor001** [comment]
That should do it: https://github.com/bkaradzic/GENie/pull/287

**Comment by KernelFreeze** [comment]
Thank you! :3 :+1:
