### ISSUE TITLE
Xcode postbuild relies on config-specfic commands happening last

### ISSUE THREAD

**Issue by fitzymj** [bkaradzic/GENie#294]
The construction of Xcode projects relies on any config-specific postbuild commands being _after_ any non-config-specific ones.  You can see that in this snippet, from `xcode_common.lua`:

```
			-- start with the project-level commands (most common)
			local prjcmds = tr.project[which]
			local commands = table.join(prjcmds, {})

			-- see if there are any config-specific commands to add
			for _, cfg in ipairs(tr.configs) do
				local cfgcmds = cfg[which]
				if #cfgcmds > #prjcmds then
					table.insert(commands, 'if [ "${CONFIGURATION}" = "' .. xcode.getconfigname(cfg) .. '" ]; then')
					for i = #prjcmds + 1, #cfgcmds do
						local cmd = cfgcmds[i]
						cmd = cmd:gsub('\\','\\\\')
						table.insert(commands, cmd)
					end
					table.insert(commands, 'fi')
				end
			end
```

To illustrate the issue, something like this:

```
configuration { "Debug" }
   postbuildcommands { "echo Debug" }
configuration { "Release" }
   postbuildcommands { "echo Release" }
configuration {}
postbuildcommands { "echo ALL" }
```

will result in the following as a build script:

```
#!/bin/sh
echo ALL
if [ "${CONFIGURATION}" = "Debug" ]; then
echo ALL
fi
if [ "${CONFIGURATION}" = "Release" ]; then
echo ALL
fi
```

**Comment by fitzymj** [comment]
It should probably see if _any_ config has commands different from the project commands?  If so, it constructs a per-config version that ignores the project commands.  If not, it uses _just_ the project commands and ignores the configs' command tables.

**Comment by bkaradzic** [comment]
What's your expected output?

```
#!/bin/sh
echo ALL
if [ "${CONFIGURATION}" = "Debug" ]; then
echo Debug
echo ALL
fi
if [ "${CONFIGURATION}" = "Release" ]; then
echo Release
echo ALL
fi
```
or:

```
#!/bin/sh
echo ALL
if [ "${CONFIGURATION}" = "Debug" ]; then
echo Debug
fi
if [ "${CONFIGURATION}" = "Release" ]; then
echo Release
fi
```

**Comment by fitzymj** [comment]
I think I'd expect it to maintain the order in which I call `postbuildcommands()`, so it'd be the first of those.  Not sure if the architecture supports that, as I haven't dug through yet to see exactly how `configurations()` works internally.

**Comment by fitzymj** [comment]
From what I can tell, that also matches the behavior of the `vs*` and `gmake` actions, which are effectively this:

```
-- see if there are any commands to add for each config
local commands = {}
for _, cfg in ipairs(tr.configs) do
   local cfgcmds = cfg[which]
   if #cfgcmds > 0 then
      table.insert(commands, 'if [ "${CONFIGURATION}" = "' .. xcode.getconfigname(cfg) .. '" ]; then')
      for i = 1, #cfgcmds do
         local cmd = cfgcmds[i]
         cmd = cmd:gsub('\\','\\\\')
         table.insert(commands, cmd)
      end
      table.insert(commands, 'fi')
   end
end
```

**Comment by bkaradzic** [comment]
Yeah it should be identical everywhere. If you have this fix for xcode you can send PR.

**Comment by bkaradzic** [comment]
Btw, generally configuration aggregates everything, so consistent with the rest of options would be:

```
#!/bin/sh
echo ALL
if [ "${CONFIGURATION}" = "Debug" ]; then
echo Debug
echo ALL
fi
if [ "${CONFIGURATION}" = "Release" ]; then
echo Release
echo ALL
fi
```

I asked because even thought it's consistent it might not be desirable because it's stream of commands, where other options are just compiler/linker options. I usually keep those pre/postbuildsteps as single external makefile/script and just invoke it at once (no complicated setup for those).

**Comment by fitzymj** [comment]
I am definitely feeling that external scripts would make this easier to maintain!  But for now this should at least get closer to correctness and consistency with other project/action types.

**Comment by bkaradzic** [comment]
For IDEs usually it's needed fix like this. Btw, a lot of platform/compiler stuff can be setup inside scripts without any internal changes. See: https://github.com/bkaradzic/bx/blob/master/scripts/toolchain.lua
