### ISSUE TITLE
Doesn't add C++ build flags when using ObjC++

### ISSUE THREAD

**Issue by codecat** [bkaradzic/GENie#306]
Seems like when adding *.mm files to a project, the flags passed to `buildoptions_cpp` are not passed to the compiler.

Take for example this C++ code, and save it as `test.cpp` and `test.mm`:

```c++
#include <atomic>

#include <cstdio>

int main()
{
	printf("Hello\n");
	return 0;
}
```

Then, use this genie.lua to build:

```lua
solution 'Test'
	language 'C++'

	configurations {
		'Debug',
		'Release'
	}

	targetdir 'bin'

	configuration '*'
		buildoptions_cpp { '-std=c++11' }

	project 'test'
		kind 'ConsoleApp'
		files {
			--'test.cpp'
			'test.mm'
		}
```

This will fail on OSX with:

```
==== Building test (debug) ====
test.mm
In file included from test.mm:1:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/atomic:543:2: error:
      <atomic> is not implemented
#error <atomic> is not implemented
 ^
1 error generated.
```

Try commenting out the .mm file in the genie script and uncommenting the .cpp file. This will now work properly.

**Comment by codecat** [comment]
I should mention that manually building the test file like this works fine:
```
g++ test.mm -std=c++11 -o test
```

**Comment by codecat** [comment]
Um.. I only just realize that `buildoptions_cpp` probably is exclusively for cpp files, now I feel stupid. The function is however not documented in the scripting reference.

**Comment by codecat** [comment]
Right. I have to use `buildoptions_objcpp`. Disregard my stupidity, apologies. :)

**Comment by bkaradzic** [comment]
buildoptions would also work, but that's just if you doing C++ projects since affects all other languages (like C)

**Comment by codecat** [comment]
Yeah, we have some C files in our project as well.

**Comment by bkaradzic** [comment]
> By the way, it would probably be good to have those functions documented, no?

Sure, send PR once you document them. :+1:
