### ISSUE TITLE
windows sdk selection

### ISSUE THREAD

**Issue by xoorath** [bkaradzic/GENie#315]
Hey,

Tried building bgfx with vs2017 on a workstation yesterday that had windows SDK 8.1 installed. The genie output selected windows SDK 8.1 as it's default target. The issue is easily resolved by selecting one of my already isntalle windows 10 SDK's as the target sdk for all projects.

I hear there's a good solution for premake4: [see here, issue 935](https://github.com/premake/premake-core/issues/935). Maybe GENie could use this solution, and bgfx could be updated to use that support?

Cheers,
xoorath

**Comment by xoorath** [comment]
I should also mention: selecting SDK 8.1 as a default causes the build to fail. That's why I needed this workaround in the first place.

**Comment by bkaradzic** [comment]
It's already supported... When your run GENie without arugments in bgfx it will show you following:

`--with-windows=#  Set the Windows target platform version (default: $WindowsSDKVersion or 8.1).`

You can specify that, or your installation of Windows SDK didn't set environment variable `WindowsSDKVersion` to appropriate version.

**Comment by xoorath** [comment]
Thank you, I'll do that.
