### ISSUE TITLE
How can I choose the output directory?

### ISSUE THREAD

**Issue by tuket** [bkaradzic/GENie#316]
In CMake I used to be able to choose where I want my project files to be generated.

For example, I have my source files in `~/myproj`. This folder contains `genie.lua`.
Then I want to generate the project files in `~/builds/myproj_vs` and `~/builds/myproj_make`.

How can I do this with GENie?

**Comment by fitzymj** [comment]
You want `location(<path>)`, after calling `solution(<name>)` or `project(<name>)`.  In the documentation here: https://github.com/bkaradzic/genie/blob/master/docs/scripting-reference.md#locationpath

**Comment by tuket** [comment]
That's exactly what I needed, thank you very much.

**Comment by bkaradzic** [comment]
Tip: If you don't see something in provided documentation, you can always look into my use cases, see: https://github.com/bkaradzic/bx/blob/master/scripts/toolchain.lua
