### ISSUE TITLE
How can I specify C++ version

### ISSUE THREAD

**Issue by tuket** [bkaradzic/GENie#317]
Hello.
I need that my application uses C++ 14. How can I do that?

**Comment by tuket** [comment]
I've found the function `cppdialect` in the premake documentation but it doesn't seem to be available in GENie.
https://github.com/premake/premake-core/wiki/cppdialect

**Comment by bkaradzic** [comment]
```lua
		buildoptions_cpp {
			"-std=c++11",
		}
```

From here:
https://github.com/bkaradzic/bx/blob/a577712b445c32beac24a134b9fb852ab9983806/scripts/toolchain.lua#L737
