### ISSUE TITLE
Add inclusion (and linking against) existing project files.

### ISSUE THREAD

**Issue by xoorath** [bkaradzic/GENie#322]
Hey,

I have a suggestion that would be quite helpful for me. I have libzmq as a dependency of my project, and they already ship with a visual studio solution and projects.

It would be very helpful to link against projects they have that already exist.

I'm not sure the alternative currently, other than writing a GENie lua for their project, and emulate their settings to re-create our own project files? If there is some easier solution that would not need this feature I'd be happy to consider this as well.

**Comment by bkaradzic** [comment]
It already supports linking with libraries. Build library and link with it. See:
https://github.com/bkaradzic/genie/blob/master/docs/scripting-reference.md#linksreferences

**Comment by xoorath** [comment]
@bkaradzic does this support this in a way that I can have my dependency's existing `.vcxproj` included in my solution generated with GENie?

Or are you just suggest I work around this by building the dependency separately and link to the build binary normally?

That's fine too, just want to be sure I understand you.

**Comment by fitzymj** [comment]
@xoorath There's an undocumented `importvsproject()` function in `api.lua` that might do something like what you want, but I've never tried it, and I'm not sure how easy it is to set up a link dependency on it.

**Comment by xoorath** [comment]
Thanks @fitzymj I'll check that out.

**Comment by xoorath** [comment]
Mostly worked out for me, thanks @fitzymj. 

This did let me add my project files to the solution. Just haven't found a way to link the projects yet. Working on that, I'll post back here if I find a solution.

**Comment by ryanjuckett** [comment]
Any progress on this? It's something I've been interested in doing as well.

**Comment by xoorath** [comment]
@ryanjuckett I've been able to use that to include the projects in the solution, but not link against them.
