### ISSUE TITLE
Xcode-OSX file hashes are different every time the projects are generated

### ISSUE THREAD

**Issue by KageKirin** [bkaradzic/GENie#324]
Hi,

I'm not sure this is a bug or just related to Xcode works, but
every time GENie re-generates an Xcode project, the file hashes are different, resulting in the project having to be rebuilt, even when there were no changes.

The correct result I would expect is that the hashes don't change, unless there are other changes in the project configuration.

Looking at the code, am I correct to assume that it's related to ```xcode.newid() ``` ?

Cheers.

**Comment by KageKirin** [comment]
Um... looking at it in detail
```
	function xcode.newid()
		return string.format("%04X%04X%04X%04X%04X%04X",
			math.random(0, 32767),
			math.random(0, 32767),
			math.random(0, 32767),
			math.random(0, 32767),
			math.random(0, 32767),
			math.random(0, 32767))
	end
``` 

Is there a meaningful way to make random more stable?

**Comment by KageKirin** [comment]
Ok, thanks. This is much simpler than my approach...
I just added md5 support to genie, i.e. https://github.com/keplerproject/md5
I'm still fighting with the integration in release config, but this is what it looks like for now
```
	function xcode.newid(node, usage)
		local base = ''

		if node.path ~= nil then
			base = base .. node.path
		elseif node.name ~= nil then
			base = base .. node.name
		end

		if usage ~= nil then
			base = base .. usage
		end

		--base = base .. tostring(node):sub(9)

		print('base:', base)
		return md5.sumhexa(base):upper():sub(0,24)
	end
```

**Comment by KageKirin** [comment]
I tried to make it simpler by using `tostring(node):sub(9)` as part of the UUID, but it figures, this is as much random as the original implementation.

**Comment by bkaradzic** [comment]
VS had similar issue before introducing UUID as hash (see prj.uuid). Try doing the same in XCode instead adding MD5.

**Comment by KageKirin** [comment]
Thanks for the hint. Much better this way:
```
	function xcode.newid(node, usage)
		local base = ''

		if node.path ~= nil then
			base = base .. node.path
		elseif node.name ~= nil then
			base = base .. node.name
		end

		if usage ~= nil then
			base = base .. usage
		end
		return os.uuid(base):upper():gsub('-',''):sub(0,24)
	end
```

**Comment by KageKirin** [comment]
@bkaradzic Would you prefer the function implementation as it is above, or would rather have another `os.uuid()` implementation (eg `os.hash12()`) that only generates 12 bytes instead of 16 and returns the hash without the '-' separators?

**Comment by bkaradzic** [comment]
Just truncate UUID to 12 bytes... :) So that it just works without specifying another thing specifically for XCode projects.

**Comment by KageKirin** [comment]
Thanks for merging.
