### ISSUE TITLE
Xcode projects - order of defines, buildoptions or flags changes when re-generating project

### ISSUE THREAD

**Issue by KageKirin** [bkaradzic/GENie#327]
Hi,
another issue I noticed, is that the order of build flags in the project seems to change randomly when re-generating the project, resulting in a full rebuild despite there being no apparent changes.

I don't know where this could come from, but sorting the tables passed to `xcode.printlist()` seems to solve it.

Any ideas?
I have a pull request in the ready.

Cheers.

**Comment by bkaradzic** [comment]
Yeah I remember doing this for other projects generators (I don't use Xcode, so I never bothered to update it). Feel free to update Xcode generator to latest Xcode (whatever is current version :).

**Comment by KageKirin** [comment]
The current XCode version is 9, but there are many good reasons not to update (bugs, mostly), so I'll keep the projects at version 8 for now.
Or I could add specific support by adding an `xcode9` target.

Also, I noticed that Xcode is modifying the projects by itself when opening them in the editor.

**Comment by bkaradzic** [comment]
> Also, I noticed that Xcode is modifying the projects by itself when opening them in the editor.

It could be some auto-upgrade process like VS has. This generator is based on Xcode4. You should diff generated project and updated one to see what Xcode is adding.

**Comment by KageKirin** [comment]
Sorry for not updating this issue, I was moved away from build system maintenance to renderer optimization for a couple of months.

It seems that in the latest releases, the `xcode10` action produces files that are not modified by xcode on load. I haven't tested this with Xcode8 or 9, but I guess we can mark this issue as resolved.
