### ISSUE TITLE
Error while generating ninja project

### ISSUE THREAD

**Issue by r-lyeh** [bkaradzic/GENie#338]
Tried to generate a simple example file and got no success.
Error log following.
Ideas?

```
Building configurations...
Running action 'ninja'...
[string "io.eol         = "\n"..."]:38: bad argument #2 to 'format' (no value)
stack traceback:
        [C]: in function 'string.format'
        [string "io.eol         = "\n"..."]:38: in function 'io.printf'
        [string "local ninja = premake.ninja..."]:113: in upvalue 'generate'
        [string "local ninja = premake.ninja..."]:80: in local 'callback'
        [string "premake._filelevelconfig = false..."]:7: in field 'generate'
        [string "local ninja = premake.ninja..."]:79: in field 'generate_ninja_builds'
        [string "premake.ninja = { }..."]:21: in field 'onsolution'
        [string "premake.action = { }..."]:19: in field 'call'
        [string "_WORKING_DIR        = os.getcwd()..."]:74: in function '_premake_main'
```

Btw, for reference, I have been using this https://github.com/jimon/premake-ninja implementation before and worked fine. Dunno if it can help with the current implementation.

**Comment by bkaradzic** [comment]
What happens if you generate project for bx or bgfx `genie --gcc=linux-gcc ninja`?

**Comment by bkaradzic** [comment]
If you're using anything from bx/scripts then you have to have appropriate path to it. GENie just operates with local stuff, and you explicitly set dependencies in your script.

**Comment by r-lyeh** [comment]
nvm. found the bug :)
this line of mine was crashing everything! `targetdir(DIR .. ".bin/%{cfg.buildcfg}")`
