### ISSUE TITLE
Add Xcode Base SDK setting

### ISSUE THREAD

**Issue by attilaz** [bkaradzic/genie#34]
With this option iOS target could be selected.

Here is how it works in the IDE:
![screen shot 2015-01-17 at 10 57 18](https://cloud.githubusercontent.com/assets/4198194/5788480/796fa398-9e38-11e4-93bc-659b42dbbf4b.png)

In xcodeproj file it possible only needs this setting in the XCBuildConfiguration section:
SDKROOT = macosx; 
or 
SDKROOT = iphoneos;

I volunteer to add this, but I am unsure if this should be a new option or use one of the currents.

**Comment by bkaradzic** [comment]
This is similar to VS toolset:
https://github.com/bkaradzic/genie/commit/7d4662ef858a29b6d385df7ddf2662724cd627f6

Adding something like `premake.xcode.toolset` would be the best.

**Comment by attilaz** [comment]
done https://github.com/bkaradzic/genie/commit/a8c03b731fc3e604a7cab088b684936493d73f5c
