### ISSUE TITLE
Scripting reference missing header/title for commands

### ISSUE THREAD

**Issue by attilaz** [bkaradzic/genie#35]
scripting-reference.md is hard to understand as there is no header/title for commands for example:

premake debugargs reference look like this:
http://industriousone.com/debugargs

but in scripting-reference.md it is just simply starts after "configurations" description
https://github.com/bkaradzic/genie/blame/master/scripting-reference.md#L345

**Comment by bkaradzic** [comment]
I'll fix it, it got lost during automatic conversion from HTML to markdown.
