### ISSUE TITLE
Linux Clang -msse3 buildoptions issue

### ISSUE THREAD

**Issue by leetNightshade** [bkaradzic/GENie#350]
I've seen projects that use the -msse3 buildoptions flag. But using that same buildoptions flag, I get compile errors trying to build the Newton Dynamics physics engine due to inlining sse3 intrinsic in a function that's not sse3 enabled. 

When I instead patch EnableSSE3 into Genie with a -msse3 CFlag, the sse3 compile error goes away. Without needing to patch Genie, is there a correct way to make sure the flag is getting through where it needs to?

Thanks.

**Comment by bkaradzic** [comment]
Only difference with EnableSSE3 would be that it handles different compilers correctly. `-msse3` is GCC/Clang only.

Can you post example of error you're getting when building?

**Comment by leetNightshade** [comment]
```In file included from ../../../libs/newton-dynamics/sdk/dgCore/dgConvexHull4d.cpp:26:
In file included from ../../../libs/newton-dynamics/sdk/dgCore/dgGoogol.h:29:
../../../libs/newton-dynamics/sdk/dgCore/dgVector.h:1389:17: error: always_inline function '_mm_hadd_ps' requires target feature 'sse3', but would be inlined into function 'AddHorizontal' that is compiled without support for 'sse3'
                dgVector tmp (_mm_hadd_ps (m_type, m_type));
                              ^
../../../libs/newton-dynamics/sdk/dgCore/dgVector.h:1390:10: error: always_inline function '_mm_hadd_ps' requires target feature 'sse3', but would be inlined into function 'AddHorizontal' that is compiled without support for 'sse3'
                return _mm_hadd_ps (tmp.m_type, tmp.m_type);
                       ^
../../../libs/newton-dynamics/sdk/dgCore/dgVector.h:1718:15: error: always_inline function '_mm_hadd_pd' requires target feature 'sse3', but would be inlined into function 'DotProduct3' that is compiled without support for 'sse3'
                __m128d dot(_mm_hadd_pd(tmp3, tmp3));
                            ^
../../../libs/newton-dynamics/sdk/dgCore/dgVector.h:1738:15: error: always_inline function '_mm_hadd_pd' requires target feature 'sse3', but would be inlined into function 'DotProduct4' that is compiled without support for 'sse3'
                __m128d dot(_mm_hadd_pd(tmp2, tmp2));
                            ^
35 warnings and 4 errors generated.
ninja: build stopped: subcommand failed.
make: *** [Makefile:14: all] Error 1
```

**Comment by leetNightshade** [comment]
I've switched away from Newton due to other issues with the library itself, but this was probably merely a config issue. I for some reason assumed "configuration" sections only covered/scoped the indented sections (that's not part of Lua); didn't realize I have to clear/switch configuration, so I had configuration leaking that caused some things to be included only part of the time.
