### ISSUE TITLE
You forgot to mention the original Premake4 author in your copyright list of the README

### ISSUE THREAD

**Issue by assarbad** [bkaradzic/GENie#355]
Since this is a fork of Premake 4.x it'd make sense, perhaps, to add Jason Perkins to the list of copyright holders in the `README.md`.

**Comment by bkaradzic** [comment]
Whole legal text is in LICENSE file: https://github.com/bkaradzic/GENie/blob/78817a9707c1a02e845fb38b3adcc5353b02d377/LICENSE#L38

README.md contains only GENie specific license.

**Comment by assarbad** [comment]
Oh, I saw the `LICENSE` file. But that's not what you get to see when you visit this project. The `README.md` is.
