### ISSUE TITLE
Wrong "WindowsTargetPlatformVersion" with vs2017

### ISSUE THREAD

**Issue by tschabo** [bkaradzic/GENie#360]
Creating projectfiles for vs2017 sets the WindowsTargetPlatformVersion to "8.1". 
I think that the rigth WindowsTargetPlatformVersion is "10.0.17134.0".
Perhaps its better to make this value configurable.

**Comment by bkaradzic** [comment]
It is already configurable, see:
https://github.com/bkaradzic/bx/blob/38600c7ac64c84b0a1b8100326fee3317ada4000/scripts/toolchain.lua#L186

https://github.com/bkaradzic/bx/blob/38600c7ac64c84b0a1b8100326fee3317ada4000/scripts/toolchain.lua#L411
