### ISSUE TITLE
How to config "C++ Language Dialect" option of XCode?

### ISSUE THREAD

**Issue by ntsjun** [bkaradzic/GENie#369]
Hi. I've tried `configuration {"C++","gcc"}
		buildoptions {
			"-std=c++11",
		}` and `configuration {"C++","gcc"}
		flags("Cpp11")`
But it seems no effect in xcode. What should I do ?

**Comment by bkaradzic** [comment]
See here: https://github.com/bkaradzic/bx/blob/e1fa528659774dcbd088e16e53b4090500b9da82/scripts/toolchain.lua#L1045

There are also flags Cpp11, Cpp14, etc. but currently not supported by Xcode.

**Comment by ntsjun** [comment]
Thanks.
