### ISSUE TITLE
What is the advantage to Premake5?

### ISSUE THREAD

**Issue by RicoP** [bkaradzic/GENie#376]
Hello,

what was the motivation to fork Premake4 and what are the advantages of GENie compared to premake5?

**Comment by bkaradzic** [comment]
Motivation:
https://github.com/bkaradzic/GENie/blob/c7e7da4aafe4210aa014a8ae8f6b01ce1d6802f0/README.md#why-fork

Premake5 wasn't usable when GENie was forked.
