### ISSUE TITLE
macOS Mojave no longer allows targeting OS X before 10.6

### ISSUE THREAD

**Issue by rb6502** [bkaradzic/GENie#384]
This broke building MAME.  The quick fix is to change all instances of "10.4" to "10.6" in build/gmake.darwin/genie.make; if you still want to support back to 10.4 things get more complicated.

**Comment by bkaradzic** [comment]
Fork GENie and maintain backward compatibility yourself, I have only latest OSX and I have no ability to test on previous versions. Apple is quite hostile when it comes to updates, so I assume everyone is always on latest.

**Comment by bkaradzic** [comment]
Ah, now it's not even backward compatible to OS that's 2 days older... :)

**Comment by rb6502** [comment]
Here's the patch I committed to MAME: https://github.com/mamedev/mame/commit/bb2eaa50ffe2bfbfc8db30be78170e80f843aa1e

It should still work with versions back to 10.6 (released in 2009) but I don't have any around to test.
