### ISSUE TITLE
os.getWindowsRegistry

### ISSUE THREAD

**Issue by amerkoleci** [bkaradzic/GENie#390]
Would be possible to add os.getWindowsRegistry?

https://github.com/premake/premake-core/blob/master/src/host/os_getWindowsRegistry.c
https://github.com/premake/premake-core/wiki/os.getWindowsRegistry

Would be useful for windows platform to detect Windows SDK from registry.

**Comment by bkaradzic** [comment]
Yes, send PR with change.
