### ISSUE TITLE
Add build support for vs2019

### ISSUE THREAD

**Issue by htmlboss** [bkaradzic/GENie#405]
The VS 2019 preview snapshot 2 has been released. It would be good to add a vs2019 flag :)

**Comment by bkaradzic** [comment]
Yes, it would be good... Send PR! ;)

**Comment by htmlboss** [comment]
You bet! Next day or two if things go well :)

**Comment by kazblox** [comment]
Please.... :)

**Comment by bkaradzic** [comment]
> You bet! Next day or two if things go well :)

I hope things went well, and everything is good, just didn't have time to do it? :)

**Comment by htmlboss** [comment]
So sorry my weekly schedule is a nightmare. I've opened a PR with what I've got so far.

**Comment by bkaradzic** [comment]
No worries, once you finish it send PR. You can find commit for VS2017 or VS2015 and see changes there. It's usually minimal amount of changes.

**Comment by rhoot** [comment]
Done in ba6ac1e.

**Comment by codecat** [comment]
Ahh nice! 👍

**Comment by howprice** [comment]
I'm having trouble with this. If I clone this repo and copy the latest Windows genie.exe into the root:

  C:\GitHub\bkaradzic\GENie>genie.exe vs2019
  Building configurations...
  Running action 'vs2019'...
  Generating genie.sln...
  [string "io.eol         = "\n"..."]:38: bad argument #2 to 'format' (no value)
  stack traceback:
        [C]: in function 'string.format'
        [string "io.eol         = "\n"..."]:38: in function '_p'
        [string "premake.vstudio.vc2010 = { }..."]:92: in field 'configurationPropertyGroup'
        [string "premake.vstudio.vc2010 = { }..."]:1136: in local 'callback'
        [string "premake._filelevelconfig = false..."]:5: in field 'generate'
        [string "premake.vstudio.vc2019 = {}..."]:25: in field 'onproject'
        [string "premake.action = { }..."]:23: in field 'call'
        [string "_WORKING_DIR        = os.getcwd()..."]:74: in function '_premake_main'

  C:\GitHub\bkaradzic\GENie>

vs2017 works just fine.

**Comment by bkaradzic** [comment]
cc @billfreist

**Comment by billfreist** [comment]
@bkaradzic the binary published in bx doesn't have all of my changes in it. Not sure if how that happened, but if I clone and build a new Genie locally, this issue @howprice is having is definitely fixed.

**Comment by bkaradzic** [comment]
Ok my bad, I forgot to push 1050...

**Comment by howprice** [comment]
That's great now thanks.
