### ISSUE TITLE
/lib/x86_64-linux-gnu/libm.so.6:  version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by MilhouseVH** [bkaradzic/GENie#409]
This has been reported downstream at [libretro-mame2016](https://github.com/libretro/mame2016-libretro/issues/23) but I figured it may be best to report it here as well, just in case.

When building `genie` with a `glibc-2.29` toolchain, executing `genie` fails as follows:
```
3rdparty/genie/bin/linux/genie: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by 3rdparty/genie/bin/linux/genie)
```

Full `libretro-mame2016` buildlog: https://pastebin.com/hVjEJcvu

The build host is Ubuntu 16.04 with `glibc-2.23`.

There is no problem building `libretro-mame2016` and `genie` on this host with a `glibc-2.28` toolchain, but it chokes with `glibc-2.29` - not sure why.

Edit to add: the exact same issue is affecting [libretro-mame](https://github.com/libretro/mame) which also uses `genie` - these are the only two packages we have found that don't get on with `glibc-2.29`. It could be there is some common issue with the mame+genie build system, or an issue with `genie`.

All other packages we are building (600+) are fine with `glibc-2.29`, so we're scratching around for ideas at this point.

**Comment by MilhouseVH** [comment]
Closing, as it turns out this was a cross-compilation issue.

**Comment by Jairo0410** [comment]
You're telling me readr library is not supported on Linux?

**Comment by mdsamiulhasan** [comment]
where is the problem solve?
