### ISSUE TITLE
How to "links" a static library file?

### ISSUE THREAD

**Issue by pratamabayu** [bkaradzic/GENie#412]
Hi @bkaradzic , 

At your documentation [about links](https://github.com/bkaradzic/GENie/blob/master/docs/scripting-reference.md#linksreferences), **there is no explanation about linking a static library file**. 

I have static library file on OSX environment and target platform.
```
-path
   -dir
      -dir
         libfoo.a
```

and I have tried to solve with

```
links {
	"foo",
}

libdirs {
	"path/dir/dir/"
}
```

but have no luck.

Do you have solution ? Correct me if I wrong.

**Comment by bkaradzic** [comment]
Yes that's correct, you probably messed up your `libdirs` path, try absolute path to make sure library file is found, and then work out relative path from your script. See examples of this in my bgfx project.
