### ISSUE TITLE
Visual Studio Code Workspace Support

### ISSUE THREAD

**Issue by pratamabayu** [bkaradzic/GENie#423]
Hi @bkaradzic 

I still use GENie for the Visual Studio (for example, Windows Desktop and WinRT development) and Xcode (for example, MacOS and iOS development) project generation. This would be better if it supports the Visual Studio Code (for example, Android and Emscripten development) project generation.

At the moment I'm still having trouble developing for Android and Emscripten because I can't find a suitable IDE. I'm curious how do you manage your bgfx project that supports Android and Emscripten?

**Comment by bkaradzic** [comment]
>  I'm curious how do you manage your bgfx project that supports Android and Emscripten?

I just use make for those platforms. I use Vim + make for most of platforms including OSX.

As for Visual Studio Code, someone who actually uses it should add support for it.

**Comment by pratamabayu** [comment]
Oh .. I see.

> I just use make for those platforms. I use Vim + make for most of platforms including OSX.

That means all of the include paths must be manually set to get intellsense in Vim?

**Comment by bkaradzic** [comment]
I don't use "intellisense" in Vim.

**Comment by pratamabayu** [comment]
So, you are coding without auto complete (suggestions) API (header)?. Sorry for my lay question. I am not yet proficient about setting up the C ++ development environment, especially for cross-platform needs.

**Comment by bkaradzic** [comment]
Yes, I don't use intellisense even in Visual Studio. I'm just not used to that type of programming.

**Comment by pratamabayu** [comment]
At the moment, it seems like the most realistic step is still to use "make" for building needs. However, for coding needs in Visual Studio Code I will parse the "Makefile" and any ".make" files to get information about the names of projects, include paths, and source paths, hoping to be able to get "intellenses" in the Visual Studio Code.
