### ISSUE TITLE
Cannot compile on Raspberry Pi due to -m64 flag

### ISSUE THREAD

**Issue by markusobi** [bkaradzic/GENie#425]
Output of `make`
```
make
lapi.c
gcc: error: unrecognized command line option ‘-m64’
```
broken since https://github.com/bkaradzic/GENie/commit/cd61236

Tested on Raspberry Pi 3B+ (Raspbian = 32 bit OS on 64 bit arm cpu)

**Comment by belegdol** [comment]
Hardcoded -m64 that genie cannot be built on any architecture different than x86_64 or ppc64le. i686 fails, armv7hl fails and so does aarch64.

**Comment by bkaradzic** [comment]
Yes... Generate project files on normal desktop, and copy it to RPi, or change GENie build script and rebuild everything...

https://github.com/bkaradzic/GENie/issues/475#issuecomment-531077834

**Comment by vadosnaprimer** [comment]
Why can't it be optional?

**Comment by bkaradzic** [comment]
It's another target for me to maintain, and number of people who use 32-bit OS is pretty low.

**Comment by belegdol** [comment]
64-bit arm does not support m64 either.
I have managed to hack up a preliminary patch, but it involves touching the generated files and I don't know how to integrate it properly. I can make a PR if this is something someone could fix up properly.
```
diff --git a/3rdparty/genie/build/gmake.linux/Makefile b/3rdparty/genie/build/gmake.linux/Makefile
index be9880cf2a..cbb63e4a2f 100644
--- a/3rdparty/genie/build/gmake.linux/Makefile
+++ b/3rdparty/genie/build/gmake.linux/Makefile
@@ -4,7 +4,7 @@
 ifndef config
   config=release
 endif
-export config
+export config M3264
 
 PROJECTS := genie
 
diff --git a/3rdparty/genie/build/gmake.linux/genie.make b/3rdparty/genie/build/gmake.linux/genie.make
index 9159acb6d3..6d30e5ae87 100644
--- a/3rdparty/genie/build/gmake.linux/genie.make
+++ b/3rdparty/genie/build/gmake.linux/genie.make
@@ -49,11 +49,11 @@ ifeq ($(config),release)
   DEFINES            += -DNDEBUG -DLUA_COMPAT_MODULE -DLUA_USE_POSIX -DLUA_USE_DLOPEN
   INCLUDES           += -I"../../src/host/lua-5.3.0/src"
   ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
-  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -Os -m64 -Wno-implicit-fallthrough
-  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -Os -m64 -Wno-implicit-fallthrough
-  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -Os -m64 -Wno-implicit-fallthrough
-  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -Os -m64 -Wno-implicit-fallthrough
-  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -Os -m64 -Wno-implicit-fallthrough
+  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -Os $(M3264) -Wno-implicit-fallthrough
+  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -Os $(M3264) -Wno-implicit-fallthrough
+  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -Os $(M3264) -Wno-implicit-fallthrough
+  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -Os $(M3264) -Wno-implicit-fallthrough
+  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -Os $(M3264) -Wno-implicit-fallthrough
   ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
   ALL_LDFLAGS        += $(LDFLAGS) -L"." -s -rdynamic
   LIBDEPS            +=
@@ -136,11 +136,11 @@ ifeq ($(config),debug)
   DEFINES            += -D_DEBUG -DLUA_COMPAT_MODULE -DLUA_USE_POSIX -DLUA_USE_DLOPEN
   INCLUDES           += -I"../../src/host/lua-5.3.0/src"
   ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
-  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m64 -Wno-implicit-fallthrough
-  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m64 -Wno-implicit-fallthrough
-  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m64 -Wno-implicit-fallthrough
-  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m64 -Wno-implicit-fallthrough
-  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g -m64 -Wno-implicit-fallthrough
+  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g $(M3264) -Wno-implicit-fallthrough
+  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g $(M3264) -Wno-implicit-fallthrough
+  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g $(M3264) -Wno-implicit-fallthrough
+  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g $(M3264) -Wno-implicit-fallthrough
+  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -g $(M3264) -Wno-implicit-fallthrough
   ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
   ALL_LDFLAGS        += $(LDFLAGS) -L"." -rdynamic
   LIBDEPS            +=
diff --git a/3rdparty/genie/makefile b/3rdparty/genie/makefile
index 7064ec9cbc..8737cab412 100644
--- a/3rdparty/genie/makefile
+++ b/3rdparty/genie/makefile
@@ -22,6 +22,22 @@ else
 OS=windows
 endif
 
+UNAME_P := $(shell uname -p)
+ifeq ($(UNAME_P),$(filter $(UNAME),x86_64,ppc64le,s390x))
+M3264=-m64
+else
+ifeq ($(UNAME_P),$(filter $(UNAME),i%86))
+M3264=-m32
+else
+ifeq ($(UNAME_P),$(filter $(UNAME),aarch64,armv%))
+M3264=
+else
+M3264=-m64
+endif
+endif
+endif
+export M3264
+
 .PHONY: release
 
 GENIE=bin/$(OS)/genie
```

**Comment by bkaradzic** [comment]
It's simple if you just remove `-m64` and regenerate files as described here:
https://github.com/bkaradzic/GENie/issues/475#issuecomment-531077834

**Comment by belegdol** [comment]
I know the fix is simple, but I was trying to come up with a solution in which make just works regardless of the architecture.

**Comment by bkaradzic** [comment]
You can just build executable and distribute with your project, no need to make it compilable from source for RPi.

**Comment by belegdol** [comment]
Shipping binaries would run afoul of Fedora packaging guidelines:
https://docs.fedoraproject.org/en-US/packaging-guidelines/what-can-be-packaged/#prebuilt-binaries-or-libraries
Other distros might have similar restrictions.
Again, removing -m64 with sed or similar on affected architectures is very simple indeed, but having it handled properly by the makefile logic would be cleaner.

**Comment by vadosnaprimer** [comment]
Otherwise the main project would just have to be forked for all those "low priority" needs. When it's caused by major overhaul it's unavoidable, but when it boils down to a tiny tweak, it's cleaner to have the option upstream. Explicit support won't even be needed, people interested in it working can handle all the related patches and send them upstream whenever something breaks.

**Comment by bkaradzic** [comment]
It would be easy to add GENie option to remove `-m64`. But you need GENie executable to run it with option to generate files. Which then implies I have to ship makefiles that are specific for 32-bit...

Again, it's maintenance burden for platforms that are not that important anyway... I ship only makefiles for Linux, Windows, OSX. I don't ship for Haiku, FreeBSD, and others, so not sure why I would treat RPi differently.

**Comment by belegdol** [comment]
It is not about the niche OSes such as FreeBSD or Haiku. The issue is that Linux distros like Fedora or Debian normally build the packages across several architectures and unless there are major issues excluding the architectures should be avoided.

Would it be possible to use an env variable approach such as in comment 6? The logic for determining whether m32, m64 or nothing is needed is already there, what is missing is to have genie put the necessary export call into gmake.linux/Makefile and the variable instead of hardcoded m64 into gmake.linux.
