### ISSUE TITLE
Set targetdir path with current platform etc

### ISSUE THREAD

**Issue by DJLink** [bkaradzic/GENie#431]
Hi,
I started to use GENie, got a small project running, but I'm trying to configure some paths to be more flexible.

How can for example set the targetdir to be different according to each configuration, let's say
./bin/x32/Debug
./bin/x32/Release
./binXx64/Debug

etc.
I saw some mentions of "%{something}" tokens in strings but it doesn't seem to work and the string is passed as it is to the project files.

Also is there any way to set targetdir to the same path as the default objdir for example? I wouldn't mind this one if the first part isn't possible.

Thanks

**Comment by bkaradzic** [comment]
See usage of targetdir in this script: https://github.com/bkaradzic/bx/blob/400a3d073b550800608a99941a792375bf5d4b7f/scripts/toolchain.lua#L562

It is possible to output binaries to specific platform/target directory.
