### ISSUE TITLE
Add support for VS2019 unity build

### ISSUE THREAD

**Issue by bkaradzic** [bkaradzic/GENie#433]
More info:
https://twitter.com/zeuxcg/status/1130854188831797253

**Comment by DJLink** [comment]
I would mind taking a look at this as I was considering this too, and actually got it working a bit, but would we target only VS2019? It seems 2017 has support too but a bit more tricky (https://devblogs.microsoft.com/cppblog/support-for-unity-jumbo-files-in-visual-studio-2017-15-8-experimental/) so maybe better only for 2019 as it works out of the box.

This would mean adding support for VS2019 on GENie as well, which shouldn't be too hard, but I have a question, right now there's specific VS2017 code on the generator, would we keep it around for 2019 too and compare if compiler is VS2017 or 2019 for those cases or maybe a way to check >=2015? this one is prob a bad idea

**Comment by bkaradzic** [comment]
> but would we target only VS2019? It seems 2017 has support too but a bit more tricky 

Only VS2019. VS2017 feature is experimental.

Yes this feature depend on https://github.com/bkaradzic/GENie/issues/405

**Comment by DJLink** [comment]
Ok, so maybe I'll wait for that commit to be merged and add Unity build on top of it, gonna put a follow on the other thread as a reminder

**Comment by bkaradzic** [comment]
That commit won't be merged because it wasn't tested enough.

**Comment by billfreist** [comment]
See commit: https://github.com/bkaradzic/GENie/commit/5ecd698971375a7c56d60e4b03bad34244e6d349
