### ISSUE TITLE
Add support for @files for gmake

### ISSUE THREAD

**Issue by KageKirin** [bkaradzic/GENie#434]
Hi,

several of the projects I'm building (for Android, using gmake) have a massive amount of source files, which when linking, hits the command line length limit in Windows.
So, I'm thinking about modifying the gmake generation part in GENie in a way to write the object/lib filenames into a "response file" (that's the term used by ninja, aka attfile or `@file`) before linking.
Basically, what the GNU Make documentation is describing [here](https://www.gnu.org/software/make/manual/html_node/File-Function.html).

So, question: would this be a generally welcome modification/improvement? Are there any edge cases I should expect, or rather should I make this behaviour optional?

Cheers.

**Comment by bkaradzic** [comment]
> So, question: would this be a generally welcome modification/improvement?

Yes, this improvement is welcome.

> Are there any edge cases I should expect, or rather should I make this behaviour optional?

No that I know of. It should be default.

Just when writing on disk make sure you're using $TMP or some other directory that's appropriate for temporary files. So that directory where makefiles are stored doesn't get bombed with these temp files.
