### ISSUE TITLE
vcxproj <ClInclude> different output between 1047 and 1050?

### ISSUE THREAD

**Issue by DJLink** [bkaradzic/GENie#445]
Hi, I recently changed to 1050 build and after running a script on my project I noticed a difference, CLInclude on the vcxproj is now writing differently, I only noticed because git was telling me a bunch of changes just by updating the build.
Previously (up to 1047)
```
  <ClInclude Include="my_file.h" />
```
and now (1050)
```
  <ClInclude Include="my_file.h">
  </ClInclude>
```

I think Visual Studio itself defaults to writing as 1047 was. It doesn't causes any problem, but now GENie doesn't generate the same output so editing directly on VS or GENie leads to different results. my question is, were this changes for any particular reason and it's working as intended or maybe by accident?
Looks like it was introduced in https://github.com/bkaradzic/GENie/commit/ef773573b1c0016dad64f0f9e33af89f1baadb7b ? 

Sorry if this was as intended.

**Comment by billfreist** [comment]
I believe its just a harmless side effect to keep the code simple. I'll let @rhoot chime in, maybe he has a simple fix in mind.

**Comment by rhoot** [comment]
Yeah I did it for simplicity cause it doesn't really change anything. If you often save project files from VS though I could see how it's annoying. Sorry about that.

**Comment by DJLink** [comment]
@rhoot no worries, and I'm sorry about that.

I almost feel bad about the next thing, but could I ask you to take a look at the following PR as well? 

Just for consistency with the other stuff I added a space " " between the " and "/>"
https://github.com/bkaradzic/GENie/pull/447

Once again thank you for your time. Sorry for being picky about this
