### ISSUE TITLE
Proposal: making the API more flexible by adding premake.fields through a function

### ISSUE THREAD

**Issue by KageKirin** [bkaradzic/GENie#453]
Hi there,

[This branch](https://github.com/KageKirin/GENie/tree/newapifield-flexible-api) is an idea and a 10min implementation of a function to make adding API fields flexible, to the point to be able to extend GENie in project lua files.

What do you think? Is that something you want? (I'll make a PR after testing this whole functionality -- for now it seems to be working without change).

EDIT: codelink 

https://github.com/KageKirin/GENie/blob/70fae0be354ab8cbcf00218a6aad4b9d184bc187/src/base/api.lua#L15-L34

**Comment by bkaradzic** [comment]
It sounds interesting. It would be good if you could extract some existing functionality into separate .lua file to test this...

cc @rhoot

**Comment by rhoot** [comment]
Seems like it could be useful, yeah.

**Comment by KageKirin** [comment]
Great. I'll commit a PR after some more testing.

**Comment by KageKirin** [comment]
Update on this: I have someting working on this branch:
https://github.com/KageKirin/GENie/tree/newapifield-flexible-api

i.e.: all api 'fields' created through `newapifield` in `api.lua`, and no regression,
and one custom field `gradlecopyassets` inside my (still not open sourced) project generation framework.

I'm currently looking for a better function name than `newapifield`, and open for better names.
