### ISSUE TITLE
Minor enhancement idea: genie default script directory

### ISSUE THREAD

**Issue by beevik** [bkaradzic/GENie#471]
GENie currently searches for default script files named `solution.lua`, `genie.lua` or `premake4.lua`.  It also searches the working directory or the `scripts` subdirectory for default scripts.

What do you think about adding the `genie` subdirectory to the list of default search subdirectories? If you're cool with it, I'll go ahead and add it.

**Comment by bkaradzic** [comment]
Sounds good to me.
