### ISSUE TITLE
Building Genie for raspberry command

### ISSUE THREAD

**Issue by OOKAMIFR** [bkaradzic/GENie#475]
hello
I am currently trying to build genie for Raspberry Pie 3 and 4
when launch command line make, command line purpose options and choose rpi but error appear

I can provide error if needed

thanks for your help

**Comment by bkaradzic** [comment]
Yeah, provide error.

**Comment by OOKAMIFR** [comment]
thanks for your answer

using this command to have genie on rpi

$ git clone https://github.com/bkaradzic/genie
$ cd genie
$ make

when launch make, there is the result
make[1] : on entre dans le répertoire « /home/pi/genie/build/gmake.linux »
==== Building genie (release) ====
lapi.c
gcc: error: unrecognized command line option ‘-m64’
make[2]: *** [genie.make:284: obj/Release/src/host/lua-5.3.0/src/lapi.o] Error 1
make[1]: *** [Makefile:17: genie] Error 2
make[1] : on quitte le répertoire « /home/pi/genie/build/gmake.linux »
make: *** [makefile:32: bin/linux/genie] Error 2

translation
on entre dans le répertoire = enter in folder directory
on quitte le répertoire = leave folder directory 

maybe something missing in order to compile it properly but can't find what is really needed
thanks for your help

**Comment by OOKAMIFR** [comment]
for complement i need to use genie in order to build bgfx as requested by this site

https://bkaradzic.github.io/bgfx/build.html
