### ISSUE TITLE
Make Freebsd issue

### ISSUE THREAD

**Issue by jeezs** [bkaradzic/GENie#481]
I try to make a FreeBSD version on FreeBSD 12 but have a few issues:
make: "/usr/home/jeezs/Desktop/genie/makefile" line 7: Missing dependency operator
make: "/usr/home/jeezs/Desktop/genie/makefile" line 8: Missing dependency operator
make: "/usr/home/jeezs/Desktop/genie/makefile" line 10: Need an operator
make: "/usr/home/jeezs/Desktop/genie/makefile" line 11: Missing dependency operator
make: "/usr/home/jeezs/Desktop/genie/makefile" line 13: Need an operator
make: "/usr/home/jeezs/Desktop/genie/makefile" line 14: Missing dependency operator
make: "/usr/home/jeezs/Desktop/genie/makefile" line 16: Need an operator
make: "/usr/home/jeezs/Desktop/genie/makefile" line 18: Need an operator
make: "/usr/home/jeezs/Desktop/genie/makefile" line 19: Need an operator
make: "/usr/home/jeezs/Desktop/genie/makefile" line 20: Need an operator
make: "/usr/home/jeezs/Desktop/genie/makefile" line 21: Need an operator
make: "/usr/home/jeezs/Desktop/genie/makefile" line 23: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/home/jeezs/Desktop/genie
How can I solve the problem?
Thanks

**Comment by zao** [comment]
BSD make and GNU make are quite different in what features they support, it seems like the top-level `makefile` for GENie is rather GNU-ish in its syntax.

Also note that the generator is documented as `GNU Makefile` in README.md, so you may have a lot of work ahead of you.

If you want a GNU make on FreeBSD, you need to install `gmake`.

**Comment by jeezs** [comment]
Ok thanks for your answer.
