### ISSUE TITLE
[ninja] wholearchive flag is ignored

### ISSUE THREAD

**Issue by KageKirin** [bkaradzic/GENie#484]
Hi again,

just discovered this right now: the `wholearchive` flag is getting completely ignored when generating ninja files, i.e. the `-Wl,whole-archive` not wrapped around the dependency libs marked as `wholearchive` in the geniefile projects.

I guess I'll go fix it and make a PR for this.

Cheers.

**Comment by bkaradzic** [comment]
> I guess I'll go fix it and make a PR for this.

:+1:

**Comment by KageKirin** [comment]
So, I went ahead and made a few PRs:

#485 the fix for this issue.
#486 supplementary fix for `-Wl,--whole-archive` having issues on OSX.
#487 a small improvement to not crash on nil argument.

#486 and #487 are not required, so feel free to close the PRs if you consider them useless.

Cheers.

**Comment by KageKirin** [comment]
Thanks for merging.
