### ISSUE TITLE
custombuildtask has a single output_file

### ISSUE THREAD

**Issue by greenkalx** [bkaradzic/GENie#495]
Is there a way to provide more than one output file to custombuildtask?

In Visual Studio, it's used to avoid running a command every time. See 'Outputs':
https://docs.microsoft.com/en-us/cpp/build/specifying-custom-build-tools?view=vs-2019

premake has a 'buildoutputs' that handles this?
https://github.com/premake/premake-core/wiki/buildcommands

I'm trying to decide on continuing with existing Visual Studio projects for Windows, and CMake for Linux. Or move to GENie or premake with the aim of having cleaner projects and being able to target other platforms (xcode..).
This CustomBuild stuff is likely the trickiest bit.
Just paste the whole section straight from the .vcxproj instead of using custombuildtask?

**Comment by greenkalx** [comment]
I found `<Outputs>` in vstudio_vcxproj.lua. My eyes are new to LUA..

**Comment by redorav** [comment]
@greenkalx If I'm understanding correctly, you just provide a list of files to buildoutputs, like so:

```lua
buildoutputs
{
    "a.output",
    "b.output"
}
```

![image](https://user-images.githubusercontent.com/700032/147672889-012769ef-d384-4ab4-ab5e-0b7f3a36b5ae.png)

**Comment by greenkalx** [comment]
closing as obsolete
