### ISSUE TITLE
[ninja] ar: difference between GNU ar (Linux) and BSD ar (BSD, macOS)

### ISSUE THREAD

**Issue by KageKirin** [bkaradzic/GENie#498]
Hi there,

I hope you're doing fine.
I stumbled over this annoying issue with responsefiles when using ninja with XCode's `ar`.

The error is the following:

```
[6/6] ar -rcs ../../bin/darwin/libflatbuffers.a @../../bin/darwin/libflatbuffers.a.rsp  2>&1 > /dev/null | sed -e '/.o) has no symbols$/d'
ar: @../../bin/darwin/libflatbuffers.a.rsp: No such file or directory
```

coming from this ninja rule:

```ninja
rule ar
  command         = ar $flags $out @$out.rsp  2>&1 > /dev/null | sed -e '/.o) has no symbols$$/d'
```

changing the line to remove the responsefile fixes it.

```ninja
rule ar
  command         = ar $flags $out $in $libs  2>&1 > /dev/null | sed -e '/.o) has no symbols$$/d'
```

So the reason for this appears to be a subtle difference between GNU `ar` and BSD `ar`:  
[GNU ar](http://man7.org/linux/man-pages/man1/ar.1.html) takes response files with the `@`, eg. `@libar.a.rsp`, while 
[BSD ar](https://www.freebsd.org/cgi/man.cgi?query=ar&sektion=1) does not support response files.

I guess, I'll prepare a fix for this...

Cheers.

**Comment by KageKirin** [comment]
> What happens when command line is really long?

You'll have you GNU ar in that case.

I quickly verified, but the manual (`man ar`) does not mention responsefiles, so yes, this needs fixing.
I'll create the PR shortly.

**Comment by bkaradzic** [comment]
cc @rhoot

**Comment by KageKirin** [comment]
#500 is the fix.

I know this changes default behavior, but it makes the behaviour similar to the gmake generator.

Alternatively, I could also rename the flags 
`UseObjectResponseFile` and `UseLDResponseFile` to `NoObjectResponseFile` and `NoLDResponseFile` respectively, and inverse the logic in `ninja_cpp.lua` and `make_cpp.lua`.

**Comment by rhoot** [comment]
I like it this way, having to opt-in to potentially unsupported behavior rather than opt out. Merged.

> What happens when command line is really long?

You're screwed, hah. But no more screwed than you were before.
