### ISSUE TITLE
Better errors when using syntax incorrectly

### ISSUE THREAD

**Issue by neilogd** [bkaradzic/genie#51]
Currently if you do something along the lines of:

    location { "loc/Path" }

You will end up with an unhelpful error with no line or callstack. Same goes if you were to go:

    include { "path/to/inc" }

You will also get an unhelpful error message.

**Comment by bkaradzic** [comment]
Isn't this just Lua thing? Any idea what would be the fix?

**Comment by jalgelind** [comment]
It fails using the error function, which should produce a stack trace. When looking at premake.c, it doesn't look like an error handler is set up for the built in scripts in release builds.
