### ISSUE TITLE
Visual Studio 2010-2019: Select platform toolset

### ISSUE THREAD

**Issue by PHarbunou** [bkaradzic/GENie#521]
Hello,
excuse me, probably, It's not an issue but more like enhancement.
May I choose "Platform Toolset" and  "Windows SDK version?" for VS2010-VS2019 solution generator?
![platform_toolset](https://user-images.githubusercontent.com/9641145/102553228-99f24280-40d3-11eb-8c37-682b34f6d0cc.png)

My current ugly workaround to setup required Platform Toolset (as example):
(replacing v140,v141,v142 (default toolset) strings with LLVM or Intel Compiler in vcxproj files)
```
genie.exe --os=windows --file=project.lua vs2015 win32 intel 
genie.exe --os=windows --file=project.lua vs2017 win32 llvm 
genie.exe --os=windows --file=project.lua vs2019 win32 llvm 
sed.exe -i "s/>v140</>Intel C++ Compiler 2021</g" "..\..\solution\win32-vs2015-intel\*.vcxproj"
del /S /Q sed*
sed.exe -i "s/>v141</>LLVM</g" "..\..\solution\win32-vs2017-intel\*.vcxproj"
del /S /Q sed*
sed.exe -i "s/>v142</>LLVM</g" "..\..\solution\win32-vs2019-intel\*.vcxproj"
del /S /Q sed*
```

**Comment by bkaradzic** [comment]
See how to select toolset: https://github.com/bkaradzic/bx/blob/7837d90865b391fd45698add941082823f5a83a6/scripts/toolchain.lua#L81-L98

How to select WindowsSDK: https://github.com/bkaradzic/bx/blob/7837d90865b391fd45698add941082823f5a83a6/scripts/toolchain.lua#L135-L139

**Comment by PHarbunou** [comment]
@bkaradzic Бранимир, I'm appologize about my stupid previous message/question. I guess, next time, I'll rebuild genie from scratch on Windows, Linux, MacOS, FreeBSD from source code (C/C++ source code + LUA) before asking you next questions.

**Comment by bkaradzic** [comment]
No problem. The best place (due lack of docs) to check features is that toolchain.lua in bx repository.

**Comment by PHarbunou** [comment]
I'm using genie since 2016-2017 , but I did not tried to build genie from source code since December, 2017 :)

**Comment by bkaradzic** [comment]
You can use these executables: https://github.com/bkaradzic/GENie#download-stable

**Comment by PHarbunou** [comment]
I'm afraid there's been some misunderstanding and it's my fault. :)
I'm already using genie 1411 binaries at least last 20-30 days (since november 2020, for my windows builds).
BTW, I've biggest collection of genie builds (binaries) :)
proof picture:
![source_code](https://user-images.githubusercontent.com/9641145/102682266-436f2c00-41d9-11eb-981f-4c0d3132e43d.png)
about build 1095 - (build from 2017) I guess, it was last build I'm tried to build from source code, instead of download your new binaries from github :)
BTW, I'm really impressed about your skills & experience (in C/C++ programming, CG, build automation, etc.). Do you have personal site? For example, I want to add link and information about you to my site: https://www.ph.life

**Comment by PHarbunou** [comment]
@bkaradzic Бранимир, Could you please enjoy us? :)) https://ph.life/friends/
