### ISSUE TITLE
What is the proper syntax for referencing a command line option in a configuration?

### ISSUE THREAD

**Issue by mlabbe** [bkaradzic/GENie#524]
The [configuration](https://github.com/bkaradzic/genie/blob/master/docs/scripting-reference.md#configurationkeywords) section of the manual states a possible value is "Command-line options - either built-in or custom".  However, there are no command line option examples in the manual.

I've tried a few things but haven't been able to get it result in a match.  If my command line parameter is `--arg=val` what should I get to return true when `arg` is specified and it equals `val`?

Happy to submit a doc PR once this is answered.

Thanks!

**Comment by bkaradzic** [comment]
It refers to this: 

I created `--gcc=` command line option:
https://github.com/bkaradzic/bx/blob/bc27026b2745bcf439a8fa969c76e04517e46305/scripts/toolchain.lua#L48

If you specify for example `--gcc=ios-arm64`:
https://github.com/bkaradzic/bx/blob/bc27026b2745bcf439a8fa969c76e04517e46305/scripts/toolchain.lua#L66

You'll be able to apply configuration settings like `configuration { "ios-arm64" }`
https://github.com/bkaradzic/bx/blob/bc27026b2745bcf439a8fa969c76e04517e46305/scripts/toolchain.lua#L1045

**Comment by mlabbe** [comment]
This is extremely helpful. Thank you.
