### ISSUE TITLE
Downloadable executable is 32-bit only

### ISSUE THREAD

**Issue by neilogd** [bkaradzic/genie#54]
Just recommended someone to use genie over premake4, and they pointed out that the executable is 64 bit only. I didn't really think many folks still used 32-bit Windows day to day, but it may be worth having the windows executable 32-bit by default?

Personally I'm fine with dumping 32-bit, but thought it might be worth raising it just in case anyone else isn't using it for this reason.

**Comment by bkaradzic** [comment]
I didn't even think of that. :) Yeah 32-bit exe is fine. I just tried building it but default script doesn't have 32/64 choice. I might look at it tomorrow.
