### ISSUE TITLE
Support for PS5, GDK Xbox and Series X/S?

### ISSUE THREAD

**Issue by Seanba** [bkaradzic/GENie#541]
Are there any plans to add support for PlayStation 5, Xbox One (GDK) , and Xbox Series X/S?

If I have it right that would include these additional platforms:
```
Prospero
Gaming.Xbox.XboxOne.x64
Gaming.Xbox.Scarlett.x64
```

**Comment by bkaradzic** [comment]
Those are NDA platforms. You won't find any info about it here, and if/when there is support there would be info how to find it in official developer forums.
