### ISSUE TITLE
FreeBSD build broken

### ISSUE THREAD

**Issue by 0-wiz-0** [bkaradzic/GENie#554]
makefile uses
```
        $(SILENT) $(MAKE) -C build/$(PROJECT_TYPE).$(OS)
```
to build, and $(OS) is set to bsd in the freebsd case https://github.com/bkaradzic/GENie/blob/master/makefile#L15 but the directory in build is called gmake.freebsd https://github.com/bkaradzic/GENie/tree/master/build/gmake.freebsd

https://github.com/bkaradzic/GENie/pull/553 contains a possible fix.

**Comment by github-c999-bfa4-cc81** [comment]
For some reason it works. The only place it does work, is the bundled old copy in MAME, where the directory has to be renamed.

**Comment by bkaradzic** [comment]
There is no maintainer for any of BSD...
