### ISSUE TITLE
Ninja: Add support for ninja (Make replacement)

### ISSUE THREAD

**Issue by balr0g** [bkaradzic/GENie#65]
It would be nice if Ninja could be supported as it's much faster for building large projects.
Project page: http://martine.github.io/ninja/
Additional info: http://www.aosabook.org/en/posa/ninja.html and http://jpospisil.com/2014/03/16/replacing-make-with-ninja.html

**Comment by bkaradzic** [comment]
:+1: Would you like to add it?

**Comment by bkaradzic** [comment]
Also I wouldn't replace really gmake, but rather just add ninja.

**Comment by balr0g** [comment]
I didn't intend to suggest removing (gnu)make support. Not sure if I'd have the time to add it. This is more of a "would be nice" thing.

**Comment by bkaradzic** [comment]
It's in PR #199.
