### ISSUE TITLE
Do not expect ldflags to be -L/usr/lib{32,64}

### ISSUE THREAD

**Issue by ramiropolla** [bkaradzic/genie#66]
In src/tools/gcc.lua, genie adds -L/usr/lib32 or -L/usr/lib64 to ldflags.

Do not do this. This is not correct. I can have a custom toolchain (cross or not) that keeps its lib files anywhere I want. You should *never* guess where the toolchain looks for its lib files.

**Comment by bkaradzic** [comment]
Fixed.
