### ISSUE TITLE
Explicit choice of linking debug or release run-time

### ISSUE THREAD

**Issue by ryanjuckett** [bkaradzic/genie#81]
I'm switching from my prior customized branch of premake to GENie and one feature I had added that is missing here is support for the explicit choice of whether to link against the debug or release run-time libraries. By default, it is implicit to use the release libs only when optimization is on or symbols are off.

The code in question can be found in 'function premake.config.isdebugbuild(cfg)' in config.lua.

I ended up adding new flags: DebugRuntime and ReleaseRuntime. Then I updated said function as follows:

	function premake.config.isdebugbuild(cfg)
		-- If any of the specific runtime flags are set
		if cfg.flags.DebugRuntime then
			return true
		end

		if cfg.flags.ReleaseRuntime then
			return false
		end

		-- If any of the optimize flags are set, it's a release a build
		if cfg.flags.Optimize or cfg.flags.OptimizeSize or cfg.flags.OptimizeSpeed then
			return false
		end

		-- If symbols are not defined, it's a release build
		if not cfg.flags.Symbols then
			return false
		end

		return true
	end

Does this sound appropriate for GENie as well? Feel free to add the code above or I could do what sounds like a pull request (?) - I literally just installed git for the first time ever so still figuring it out.

**Comment by bkaradzic** [comment]
Wouldn't be better to just have `DebugRuntime` and then add it here:
https://github.com/bkaradzic/genie/blob/master/src/actions/vstudio/vs2010_vcxproj.lua#L152
and here:
https://github.com/bkaradzic/genie/blob/master/src/actions/vstudio/vs200x_vcproj.lua#L270

**Comment by ryanjuckett** [comment]
*If* you want to maintain the current logic when the user doesn't specify anything, then you need three states: 
a) force debug
b) force release
c) guess based on other settings

That's why I added the two flags separately. If you wanted to remove the current isdebugbuild logic and just test a single DebugRuntime flag, I could see your suggestion working. Not sure if that is what you meant, though.

**Comment by bkaradzic** [comment]
I meant this:

    if premake.config.isdebugbuild(cfg) or cfg.flags.DebugRuntime then

If it is debug build, or you specified `DebugRuntime` it uses debug runtime, otherwise uses release runtime.

**Comment by ryanjuckett** [comment]
How would to you tell it to link the Release Runtime in an unoptimized build?

**Comment by bkaradzic** [comment]
Ah I get it. The problem I see with multiple symbols is that can cause problems, when something defines `DebugRuntime`, and then later adds `ReleaseRuntime`, that second one would get ignored.

**Comment by ryanjuckett** [comment]
Yeah. It's be no means a perfect solution - just the one I used because it was simple :)  You could also have some enum-ish config option like 'runtime=debug'

**Comment by bkaradzic** [comment]
Actually I have idea, when it's not specified:

    flags { "DebugRuntime" }

It defaults to:

    DebugRuntime = premake.config.isdebugbuild(cfg)

You can use:

    removeflags { "DebugRuntime" }

to disable DebugRuntime.

**Comment by ryanjuckett** [comment]
Does that cause any issues with setting the flag at solution scope versus project scope? I forget how the internals cascade options between sibling projects. In other words, does it need to get reevaluated as isdebugbuild at the start of each new project if not set by the solution? Assuming there are no problems there, it sounds fine to me.

**Comment by bkaradzic** [comment]
It's evaluated per project/config. Try it, I think it will work.

**Comment by ryanjuckett** [comment]
Will do.

**Comment by ryanjuckett** [comment]
Thinking about his more I don't think it will work. Where are you expecting that default to be set? For the default thing to happen the order would need to be:

1) User sets all of their optimize flags
2) Set DebugRuntime based on the optimize flags
3) User sets or removes DebugRuntime to explicitly force the field
4) Flags are evaluated

I don't see how step 1 and 3 would be separated unless you can detect that the user never set or removed the flag and thus can set it to a default value based on the other flags after step 3.

Does that make sense to you or am I missing something?

**Comment by bkaradzic** [comment]
Nope, you're right.

**Comment by ryanjuckett** [comment]
So like half a year later I've managed to take the time and learn the basics of git :)

I have the flag based solution functional in my branch and have been using it since May. If you want a pull request for it, just let me know. It hasn't been worth the effort on my end to get a cleaner, non-binary version up and running. I understand if you want to hold the line on that architectural nicety.

**Comment by bkaradzic** [comment]
> I understand if you want to hold the line on that architectural nicety.

It depends, my biggest concern is maintainability. Can you link your commit so that I can see how complex change is?

**Comment by ryanjuckett** [comment]
I can try.  https://github.com/ryanjuckett/genie/commit/8547f3cd89f1c584525ddcc19161c0344ea348fc

**Comment by bkaradzic** [comment]
Oh yeah this is simple :+1: PR. :)

**Comment by ryanjuckett** [comment]
perfect
