### ISSUE TITLE
The <UniqueIdentifier> property for vcxproj filters isn't calling os.uuid with string input

### ISSUE THREAD

**Issue by ryanjuckett** [bkaradzic/genie#82]
When outputting unique ids for filters in vcxproj files, the code is currently
    _p(3, '<UniqueIdentifier>{%s}</UniqueIdentifier>', os.uuid())

This results in the id changing with every generation.

I've done this in the past:
    _p(3, '<UniqueIdentifier>{%s}</UniqueIdentifier>', os.uuid(path))

If filters had the same path the id would end up the same, but not sure if that is possible or causes a problem. I never encountered it in my small sample set of me.

**Comment by bkaradzic** [comment]
Yeah that feature exist. You can add that feature.
