### ISSUE TITLE
XCode generation doesn't appear to support buildoptions_cpp

### ISSUE THREAD

**Issue by fuzzybinary** [bkaradzic/GENie#87]
adding:

```
buildoptions_cpp {
     "-std=c++11"    
}
```

Doesn't add that flag to the C++ build options in xcode4. Using "buildoptions" adds the flag to both the C and C++ versions.

**Comment by bkaradzic** [comment]
@mmicko can you check this issue?

**Comment by mmicko** [comment]
Sorry for late reply, but problem with XCode and VS is that they do not have per-file compile options but just per project. What I can add is that in case it is C++ project (or ForceCPP) to use buildoptions + buildoptions_cpp  and for C projects buildoptions + buildoptions_c. Would that be fine for you ?

**Comment by fuzzybinary** [comment]
XCode (at least XCode 5) has a separate project level option for C vs C++ build options (it's OTHER_CPLUSPLUSFLAGS for C++) 

I'm not sure how Genie / Premake work internally, but would it be possible to assign buildoptions + buildoptions_cpp to OTHER_CPLUSPLUSFLAGS and buildoptions + buildoptions_c to OTHER_CFLAGS?

**Comment by mmicko** [comment]
Yes it could be possible.

There is line
xcode.printlist(table.join(flags, cfg.buildoptions), 'OTHER_CFLAGS')

so new code would be :

xcode.printlist(table.join(flags, cfg.buildoptions, cfg.buildoptions_c),
'OTHER_CFLAGS')

xcode.printlist(table.join(flags, cfg.buildoptions, cfg.buildoptions_cpp), '
OTHER_CPLUSPLUSFLAGS')

**Comment by JeffProgrammer** [comment]
I should have read this before opening issue #88

**Comment by fuzzybinary** [comment]
Closing as resolved 5 years after it was resolved 🙃
