### ISSUE TITLE
XCode c++11

### ISSUE THREAD

**Issue by JeffProgrammer** [bkaradzic/GENie#88]
Making genie work in a c++11 macosx project is failing to compile on xcode unless I manually go in and change the c++ language dialect option to c++11. I tried using linkoptions but it doesn't seem to work. Is there any other way of enabling c++11? I'm using xcode 6.2

What I tried:
```
	linkoptions {
		"-std=c++11",
	}
```

**Comment by bkaradzic** [comment]
Try:

    buildoptions_cpp {
        "-std=c++11",
    }

**Comment by JeffProgrammer** [comment]
nope, didn't work. same result :(

**Comment by JeffProgrammer** [comment]
this was merged in. closing this.
