### ISSUE TITLE
Generated VS2015 C# projects only contain the AnyCPU target platform

### ISSUE THREAD

**Issue by ahillo** [bkaradzic/genie#97]
Trying to generate project files with the following lua configuration generates a project with only the AnyCPU platform available. I assumed a .csproj file with the x86 and x64 target platforms would have been generated

```
project "project"
	uuid "17159639-a14d-42de-ba6a-5d029ead90b6"
	kind "SharedLib"
	language "C#"
	flags("Unsafe")

	configurations { "Debug", "Release" }
	platforms { "x32", "x64" }

	files {
		"../source/project/**.cs",
	}
```
 Correct platforms are generated when changing *language* to "C++".

**Comment by bkaradzic** [comment]
C#, won't fix. ;) I should probably delete support for it too, so it's more obvious.

**Comment by ahillo** [comment]
So I should create my own fork because I like to use C# where it's a better option and C/C++ elsewhere? Or perhaps it makes no sense to use genie for cross-platform C# code because there are at least some attempts at standardizing the build process. I was mainly interested in this feature because having C/C++ code in the project means I need to use genie (or something similar) anyway.

**Comment by bkaradzic** [comment]
I don't have problem if you want to maintain C# project gen code path. But I don't use C# on any platform, and don't know anything about it.

**Comment by bkaradzic** [comment]
Also just FYI, in case this can help you with C#:

MSBuild is going cross-platform with .NET Core
http://blogs.msdn.com/b/dotnet/archive/2015/09/03/msbuild-is-going-cross-platform-with-net-core.aspx
