### ISSUE TITLE
Error: Cannot install on MacOSX10.10.5

### ISSUE THREAD

**Issue by aelialper** [bkaradzic/genie#99]
==== Building genie (release) ====
os_getversion.c
In file included from /usr/include/Availability.h:153:0,
                 from /usr/include/stdio.h:65,
                 from ../../src/host/lua-5.3.0/src/lauxlib.h:13,
                 from ../../src/host/premake.h:9,
                 from ../../src/host/os_getversion.c:7:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262:38: error: expected ',' or '}' before '__attribute__'
   kFSEventStreamCreateFlagIgnoreSelf __OSX_AVAILABLE_STARTING(__MAC_10_6, __IPHONE_6_0) = 0x00000008,
                                      ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414:38: error: expected ',' or '}' before '__attribute__'
   kFSEventStreamEventFlagItemCreated __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_6_0) = 0x00000100,
                                      ^
make[2]: *** [obj/Release/src/host/os_getversion.o] Error 1
make[1]: *** [genie] Error 2
make: *** [bin/darwin/genie] Error 2

**Comment by bkaradzic** [comment]
It should be fixed.
